"use client";

import React from "react";
import { Database, Search, ArrowUpDown, AlertTriangle } from "lucide-react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  Input,
} from "@/components/atoms";
import { useBatchReportsTable } from "@/hooks";
import { MonitoringConfig, DailySummaryResponse } from "@/types/features";

interface BatchReportsTableProps {
  summaries: DailySummaryResponse[];
  configs: MonitoringConfig[];
  isLoading: boolean;
}

export function BatchReportsTable({
  summaries,
  configs,
  isLoading,
}: BatchReportsTableProps) {
  const {
    searchQuery,
    setSearchQuery,
    activeConfigFilter,
    setActiveConfigFilter,
    toggleSort,
    filteredSummaries,
  } = useBatchReportsTable({ summaries });

  return (
    <Card className="border border-border/40 bg-card/25 shadow-sm p-6">
      <CardHeader className="px-0 pt-0 pb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <CardTitle className="text-sm font-bold flex items-center gap-2">
            <Database className="h-4.5 w-4.5 text-primary" />
            Pipeline Summary Reports
          </CardTitle>
          <CardDescription className="text-xs">
            Review and audit historic daily summary records generated by manual
            or cron triggers.
          </CardDescription>
        </div>

        {/* SEARCH & FILTERS BAR */}
        <div className="flex flex-wrap items-center gap-2">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground/50" />
            <Input
              type="text"
              placeholder="Search url..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-muted/40 dark:bg-slate-950/40 border border-border/25 rounded-lg pl-8 pr-3 py-1.5 text-xs text-foreground outline-none transition-colors focus:border-primary/50 min-w-40 sm:min-w-56"
            />
          </div>

          <select
            value={activeConfigFilter}
            onChange={(e) => setActiveConfigFilter(e.target.value)}
            className="bg-muted/40 dark:bg-slate-950/40 border border-border/25 rounded-lg px-2.5 py-1.5 text-xs text-foreground outline-none transition-colors focus:border-primary/50"
          >
            <option value="all">All Targets</option>
            {configs.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
        </div>
      </CardHeader>

      <CardContent className="px-0 pb-0">
        <div className="border border-border/20 rounded-xl overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-muted/15 border-b border-border/20 text-[10.5px] font-bold text-muted-foreground/70 uppercase tracking-wider select-none">
                <th
                  className="px-4 py-3 cursor-pointer hover:text-foreground transition-colors"
                  onClick={() => toggleSort("date")}
                >
                  <div className="flex items-center gap-1.5">
                    Batch Date
                    <ArrowUpDown className="h-3 w-3" />
                  </div>
                </th>
                <th className="px-4 py-3">Config / Website Target</th>
                <th
                  className="px-4 py-3 cursor-pointer hover:text-foreground transition-colors"
                  onClick={() => toggleSort("uptime")}
                >
                  <div className="flex items-center gap-1.5">
                    Uptime Ratio
                    <ArrowUpDown className="h-3 w-3" />
                  </div>
                </th>
                <th
                  className="px-4 py-3 cursor-pointer hover:text-foreground transition-colors"
                  onClick={() => toggleSort("latency")}
                >
                  <div className="flex items-center gap-1.5">
                    Avg Latency
                    <ArrowUpDown className="h-3 w-3" />
                  </div>
                </th>
                <th className="px-4 py-3">Downtimes</th>
                <th className="px-4 py-3">Total Checks</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/10 text-xs text-foreground/80">
              {isLoading ? (
                Array.from({ length: 4 }).map((_, i) => (
                  <tr key={i}>
                    {Array.from({ length: 6 }).map((_, j) => (
                      <td key={j} className="px-4 py-3.5">
                        <div className="h-4 animate-pulse bg-muted/30 rounded-md" />
                      </td>
                    ))}
                  </tr>
                ))
              ) : filteredSummaries.length > 0 ? (
                filteredSummaries.map((summary) => (
                  <tr
                    key={summary.id}
                    className="hover:bg-muted/5 transition-colors"
                  >
                    <td className="px-4 py-3.5 font-mono font-bold text-muted-foreground">
                      {summary.date}
                    </td>
                    <td className="px-4 py-3.5">
                      <div className="font-semibold text-foreground/90">
                        {configs.find((c) => c.id === summary.configId)?.name ||
                          "Target"}
                      </div>
                      <div
                        className="text-[10px] text-muted-foreground/60 font-mono truncate max-w-64"
                        title={summary.url}
                      >
                        {summary.url}
                      </div>
                    </td>
                    <td className="px-4 py-3.5">
                      <Badge
                        variant="outline"
                        className={`font-mono font-bold text-[10px] border-none px-2 py-0.5 ${
                          summary.uptimePercent === 100
                            ? "bg-emerald-500/10 text-emerald-500"
                            : summary.uptimePercent >= 99
                              ? "bg-emerald-500/5 text-emerald-400"
                              : summary.uptimePercent >= 95
                                ? "bg-amber-500/10 text-amber-500"
                                : "bg-red-500/10 text-red-500"
                        }`}
                      >
                        {summary.uptimePercent.toFixed(3)}%
                      </Badge>
                    </td>
                    <td className="px-4 py-3.5 font-mono font-semibold">
                      {summary.avgLatencyMs} ms{" "}
                      <span className="text-[10.5px] text-muted-foreground/50 font-normal">
                        ({summary.minLatencyMs}-{summary.maxLatencyMs})
                      </span>
                    </td>
                    <td className="px-4 py-3.5">
                      {summary.downtimeIncidents > 0 ? (
                        <Badge
                          variant="outline"
                          className="border-red-500/20 bg-red-500/5 text-red-400 font-bold text-[9px] uppercase tracking-wider gap-1"
                        >
                          <AlertTriangle className="h-3 w-3" />
                          {summary.downtimeIncidents} fails
                        </Badge>
                      ) : (
                        <span className="text-muted-foreground/50 font-medium">
                          None
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3.5 font-mono font-medium text-muted-foreground/80">
                      {summary.totalChecks.toLocaleString("id-ID")}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan={6}
                    className="text-center py-8 text-muted-foreground/55 italic bg-muted/5"
                  >
                    No matching historical logs found in search.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}
