import { ROLES, type Role } from "./roles";
import { PERMISSIONS, type Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.PIC]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.TASK_REORDER,
    PERMISSIONS.TIMELINE_MANAGE,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_UPDATE,
    PERMISSIONS.ISSUE_RESOLVE,
  ],

  [ROLES.FE]: [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.TASK_REORDER,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.ISSUE_CREATE,
  ],

  [ROLES.BE]: [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.TASK_REORDER,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.ISSUE_CREATE,
  ],

  [ROLES.QA]: [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.ISSUE_CREATE,
    PERMISSIONS.ISSUE_UPDATE,
    PERMISSIONS.ISSUE_RESOLVE,
  ],

  [ROLES.BA]: [
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.TIMELINE_MANAGE,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
  ],

  [ROLES.UIUX]: [
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ARCHIVE,
    PERMISSIONS.TIMELINE_MANAGE,
    PERMISSIONS.DAILY_LOG_CREATE,
    PERMISSIONS.DAILY_LOG_VIEW,
  ],
};
